server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.study.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring的配置
spring:
  application:
    name: spring-cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

# Eureka配置，服务注册
eureka:
  client:
    service-url:
#      defaultZone: http://eureka-7001:7001/eureka,http://eureka-7002:7002/eureka,http://eureka-7003:7003/eureka
      defaultZone: http://eureka-single-7001:7001/eureka
  instance:
    instance-id: spring-cloud-provider # 修改eureka上默认的描述信息：localhost:spring-cloud-provider:8001 --> spring-cloud-provider

# info配置，通过访问http://localhost:8001/actuator/info看到对应的信息
info:
  app.name: spring-cloud-provider
  company.name: study.springcloud.com